import argparse
import asyncio
import signal
from pathlib import Path

import redis.asyncio as redis_lib

from worker.src.agent import WorkerAgent
from worker.src.config import WorkerConfig
from worker.src.consumer import TaskConsumer
from worker.src.executor import create_executor

CONFIG_FILE = Path("worker/.env")


def _save_credentials(config: WorkerConfig, agent: WorkerAgent) -> None:
    """Append worker credentials to the worker .env file (like gitlab-runner config.toml)."""
    lines: list[str] = []
    if CONFIG_FILE.exists():
        text = CONFIG_FILE.read_text()
        # Remove old credential lines
        lines = [
            line for line in text.splitlines()
            if not line.startswith(("BSNEXUS_WORKER_ID=", "BSNEXUS_WORKER_TOKEN=",
                                    "BSNEXUS_SERVER_URL=", "BSNEXUS_REDIS_URL=",
                                    "BSNEXUS_EXECUTOR_TYPE=", "BSNEXUS_WORKER_NAME="))
        ]

    lines.extend([
        "",
        "# Registered worker credentials (auto-generated by 'bsnexus-worker register')",
        f"BSNEXUS_SERVER_URL={config.server_url}",
        f"BSNEXUS_REDIS_URL={config.redis_url}",
        f"BSNEXUS_EXECUTOR_TYPE={config.executor_type}",
        f"BSNEXUS_WORKER_NAME={agent.worker_id and config.worker_name or ''}",
        f"BSNEXUS_WORKER_ID={agent.worker_id}",
        f"BSNEXUS_WORKER_TOKEN={agent.token}",
    ])

    CONFIG_FILE.write_text("\n".join(lines) + "\n")


async def _run_loop(agent: WorkerAgent, config: WorkerConfig) -> None:
    """Core event loop: heartbeat + task consumption."""
    redis_client = redis_lib.from_url(config.redis_url, decode_responses=True)
    executor = create_executor(config.executor_type)
    consumer = TaskConsumer(redis_client, agent, executor)

    print(f"Worker {agent.worker_id} listening for tasks... (Ctrl+C to stop)")

    # Graceful shutdown
    loop = asyncio.get_running_loop()
    for sig in (signal.SIGTERM, signal.SIGINT):
        loop.add_signal_handler(sig, lambda: asyncio.create_task(agent.shutdown()))

    tasks = [
        asyncio.create_task(agent.heartbeat_loop()),
        asyncio.create_task(consumer.task_loop()),
        asyncio.create_task(consumer.qa_loop()),
    ]

    if config.duration:
        tasks.append(asyncio.create_task(asyncio.sleep(config.duration)))
        done, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)
        for t in pending:
            t.cancel()
        await agent.shutdown()
    else:
        try:
            await asyncio.gather(*tasks)
        except asyncio.CancelledError:
            pass

    await redis_client.close()


async def register(config: WorkerConfig) -> None:
    """Register this worker, save credentials, and start the event loop."""
    agent = WorkerAgent(config)
    await agent.register()

    _save_credentials(config, agent)

    print(f"Worker registered: id={agent.worker_id}")
    print(f"Credentials saved to {CONFIG_FILE}")

    await _run_loop(agent, config)


async def run(config: WorkerConfig) -> None:
    """Start the worker event loop using saved credentials."""
    if not config.worker_id or not config.worker_token:
        print("Error: No worker credentials found.")
        print("Run 'bsnexus-worker register' first.")
        return

    agent = WorkerAgent(config)
    # Re-register to refresh Redis state and get stream info
    await agent.register()

    await _run_loop(agent, config)


def cli_main() -> None:
    parser = argparse.ArgumentParser(description="BSNexus Worker")
    subparsers = parser.add_subparsers(dest="command")

    # --- register subcommand ---
    reg_parser = subparsers.add_parser("register", help="Register this worker and save credentials")
    reg_parser.add_argument("--url", required=True, help="BSNexus server URL (e.g. http://localhost:8000)")
    reg_parser.add_argument("--token", required=True, help="Registration token from the admin UI")
    reg_parser.add_argument("--redis-url", default=None, help="Redis URL (default: redis://localhost:6379)")
    reg_parser.add_argument("--executor", default="claude-code", help="Executor type (default: claude-code)")
    reg_parser.add_argument("--name", default=None, help="Worker display name (auto-generated if omitted)")

    # --- run subcommand ---
    run_parser = subparsers.add_parser("run", help="Start worker using saved credentials")
    run_parser.add_argument("--duration", type=int, default=None, help="Max run time in seconds")

    args = parser.parse_args()

    if args.command == "register":
        kwargs: dict = {
            "server_url": args.url,
            "registration_token": args.token,
            "executor_type": args.executor,
            "worker_name": args.name,
        }
        if args.redis_url:
            kwargs["redis_url"] = args.redis_url
        config = WorkerConfig(**kwargs)
        asyncio.run(register(config))

    elif args.command == "run":
        config = WorkerConfig()
        if args.duration:
            config = WorkerConfig(duration=args.duration)
        asyncio.run(run(config))

    else:
        parser.print_help()


if __name__ == "__main__":
    cli_main()
