"""add security tables (audit_logs, api_keys, data_processing_records, consent_records)

Revision ID: 7e7c56acd1a0
Revises: h9c0d1e2f3a4
Create Date: 2026-02-19 01:40:08.211539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e7c56acd1a0'
down_revision: Union[str, Sequence[str], None] = 'h9c0d1e2f3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('key_prefix', sa.String(length=10), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', 'viewer', 'worker', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index('ix_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False)
    op.create_index('ix_api_keys_role', 'api_keys', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action', sa.Enum('auth_login', 'auth_logout', 'auth_failed', 'auth_token_created', 'auth_token_revoked', 'worker_registered', 'worker_deregistered', 'worker_heartbeat_failed', 'data_read', 'data_created', 'data_updated', 'data_deleted', 'data_exported', 'admin_settings_changed', 'admin_config_changed', 'security_rate_limited', 'security_invalid_input', 'security_unauthorized', 'security_prompt_tampered', 'security_audit_requested', 'task_state_changed', 'task_assigned', name='auditaction'), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'error', 'critical', name='auditseverity'), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('actor_type', sa.String(length=50), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action_timestamp', 'audit_logs', ['action', 'timestamp'], unique=False)
    op.create_index('ix_audit_logs_actor_timestamp', 'audit_logs', ['actor_id', 'timestamp'], unique=False)
    op.create_index('ix_audit_logs_severity', 'audit_logs', ['severity'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject_id', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('withdrawal_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_subject_id'), 'consent_records', ['subject_id'], unique=False)
    op.create_table('data_processing_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('data_categories', sa.Text(), nullable=False),
    sa.Column('data_subjects', sa.String(length=255), nullable=False),
    sa.Column('retention_period', sa.String(length=100), nullable=False),
    sa.Column('legal_basis', sa.String(length=255), nullable=False),
    sa.Column('recipients', sa.Text(), nullable=True),
    sa.Column('third_country_transfers', sa.Text(), nullable=True),
    sa.Column('security_measures', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('registration_tokens_token_key'), 'registration_tokens', type_='unique')
    op.drop_index(op.f('ix_registration_tokens_token'), table_name='registration_tokens')
    op.create_index(op.f('ix_registration_tokens_token'), 'registration_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_tokens_token'), table_name='registration_tokens')
    op.create_index(op.f('ix_registration_tokens_token'), 'registration_tokens', ['token'], unique=False)
    op.create_unique_constraint(op.f('registration_tokens_token_key'), 'registration_tokens', ['token'], postgresql_nulls_not_distinct=False)
    op.drop_table('data_processing_records')
    op.drop_index(op.f('ix_consent_records_subject_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index('ix_audit_logs_severity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_timestamp', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_api_keys_role', table_name='api_keys')
    op.drop_index('ix_api_keys_key_hash', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
